import{a as S,S as q,i as s}from"./assets/vendor-67BWzQEt.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const i of t.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function a(e){if(e.ep)return;e.ep=!0;const t=n(e);fetch(e.href,t)}})();const v="https://pixabay.com/api/",B="50786624-1add8080b253d44feed6410de";function d(r,o){return S(v,{params:{key:B,q:r,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}}).then(n=>n.data)}const u=document.querySelector(".gallery"),m=document.querySelector(".loader"),p=document.querySelector(".load-more"),E=new q(".gallery a",{captionsData:"alt",captionPosition:"bottom",captionDelay:250,overlayOpacity:.3});function f(r){const o=r.map(({webformatURL:n,largeImageURL:a,tags:e,likes:t,views:i,comments:b,downloads:w})=>`
      <li class="gallery-item">
        <a href="${a}">
          <img src="${n}" alt="${e}" />
        </a>
        <div class="gallery-info">
          <p><b>Likes:</b> ${t}</p>
          <p><b>Views:</b> ${i}</p>
          <p><b>Comments:</b> ${b}</p>
          <p><b>Downloads:</b> ${w}</p>
        </div>
      </li>`).join("");u.insertAdjacentHTML("beforeend",o),E.refresh()}function M(){u.innerHTML=""}function h(){m.classList.remove("hidden")}function g(){m.classList.add("hidden")}function y(){p.classList.remove("hidden")}function L(){p.classList.add("hidden")}const P=document.querySelector(".form"),$=document.querySelector('input[name="search-text"]'),O=document.querySelector(".load-more");let l="",c=1;P.addEventListener("submit",R);O.addEventListener("click",x);function R(r){r.preventDefault();const o=$.value.trim();if(!o){s.error({title:"Error",message:"Please enter a search query.",position:"topRight"});return}l=o,c=1,h(),L(),M(),d(l,c).then(n=>{if(n.hits.length===0){s.warning({title:"No Results",message:"No images found. Try another query!",position:"center"});return}f(n.hits),y()}).catch(()=>{s.error({title:"Error",message:"Something went wrong. Try again later.",position:"topRight"})}).finally(()=>g())}function x(){c+=1,h(),L(),d(l,c).then(r=>{f(r.hits),y();const{height:o}=document.querySelector(".gallery li").getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}).catch(()=>{s.error({title:"Error",message:"Something went wrong while loading more.",position:"topRight"})}).finally(()=>g())}
//# sourceMappingURL=index.js.map
